### ISSUE TITLE
Does the lib work?

### ISSUE THREAD

**Issue by bl9l** [Nerixyz/instagram_mqtt#1]
Hi.
I launched the `main.ts` file with my credentials and only message that I receive is:
`/t_region_hint
[
    "FRC"
]`
So when any activity is going on my account, I do not receive notifications. 
Notifications are enabled and I receive them on my phone.

Can you give any feedback?

**Comment by Nerixyz** [comment]
Fbns is for notifications and is currently not working. In the test branch I've added a new mqtt implementation and am trying to get it working.

**Comment by bl9l** [comment]
Thanks
