### ISSUE TITLE
markAsSeen not working

### ISSUE THREAD

**Issue by SAkhoundi** [Nerixyz/instagram_mqtt#112]
thank you for great project
but for me the markAsSeen not working and get badrequest error

`   ig.realtime.on('receive', (topic, messages) => console.log('receive', topic, messages));
        
            // this is called with a wrapper use {message} to only get the "actual" message from the wrapper
            ig.realtime.on('message',(a)=>{console.log('message',a)});
        
            // a thread is updated, e.g. admins/members added/removed
            ig.realtime.on('threadUpdate',(a)=>{console.log('threadUpdate',JSON.stringify (a))});
        
            // other direct messages - no messages
            ig.realtime.on('direct',(a)=>{console.log('direct',JSON.stringify( a))});
        
            // whenever something gets sent to /ig_realtime_sub and has no event, this is called
            ig.realtime.on('realtimeSub',(a)=>{console.log('realtimeSub',JSON.stringify( a));});
        
            // whenever the client has a fatal error
            ig.realtime.on('error', console.error);
        
            ig.realtime.on('close', () => console.error('close','RealtimeClient closed'));
        
            // connect
            // this will resolve once all initial subscriptions have been sent
            await ig.realtime.connect({
                // optional
                graphQlSubs: [
                    // these are some subscriptions
                    GraphQLSubscriptions.getAppPresenceSubscription(),
                    GraphQLSubscriptions.getZeroProvisionSubscription(ig.StateData.DeviceInfo.DeviceGuid),
                    GraphQLSubscriptions.getDirectStatusSubscription(),
                    GraphQLSubscriptions.getDirectTypingSubscription(ig.StateData.UserSession.LoggedInUser.Pk.toString()),
                    GraphQLSubscriptions.getAsyncAdSubscription(ig.StateData.UserSession.LoggedInUser.Pk.toString()),
                ],
                // optional
                skywalkerSubs: [
                    SkywalkerSubscriptions.directSub(ig.StateData.UserSession.LoggedInUser.Pk.toString()),
                    SkywalkerSubscriptions.liveSub(ig.StateData.UserSession.LoggedInUser.Pk.toString()),
                ],
                // optional
                // this enables you to get direct messages
                irisData:{
        seq_id:672,
        snapshot_at_ms:1707312881567
                },
                // optional
                // in here you can change connect options
                // available are all properties defined in MQTToTConnectionClientInfo
                connectOverrides: {},
        
                // optional
                // use this proxy
            });
        
            // simulate turning the device off after 2s and turning it back on after another 2s
            // setTimeout(() => {
            //     console.log('Device off');
            //     // from now on, you won't receive any realtime-data as you "aren't in the app"
            //     // the keepAliveTimeout is somehow a 'constant' by instagram
            //     ig.realtime.direct.sendForegroundState({
            //         inForegroundApp: false,
            //         inForegroundDevice: false,
            //         keepAliveTimeout: 900,
            //     });
            // }, 2000);
            // setTimeout(() => {
            //     console.log('In App');
            //     ig.realtime.direct.sendForegroundState({
            //         inForegroundApp: true,
            //         inForegroundDevice: true,
            //         keepAliveTimeout: 60,
            //     });
            // }, 4000);
        
            // an example on how to subscribe to live comments
            // you can add other GraphQL subs using .subscribe
            await ig.realtime.graphQlSubscribe(GraphQLSubscriptions.getLiveRealtimeCommentsSubscription('<broadcast-id>'));
            setTimeout(() => {            ig.realtime.direct.markAsSeen({threadId:'340282366841710301244276136644474698755',itemId:'31494381493059910729266784534265856'});
            }, 20000);`

**Comment by Nerixyz** [comment]
The library is a bit old, and they probably changed the minimum version (the version this library emulates is quite old).

**Comment by SAkhoundi** [comment]
Is there any way to extract the connection?
i used the instagram on fiddler

**Comment by Nerixyz** [comment]
You should be able to see the packets with any tool that can decrypt TLS connections. I used mitmproxy, but fiddler might work too,

**Comment by SAkhoundi** [comment]
But on fiddler realtime stop working

**Comment by SAkhoundi** [comment]
I use internal white hat option to intercept packets but in the inbox component stop working

**Comment by SAkhoundi** [comment]
I found the answer.
mark seen not on MQTT more
it is on API

**Comment by SAkhoundi** [comment]
I found the answer.
mark seen not on MQTT more
it is on API

**Comment by SAkhoundi** [comment]
I found the answer.
mark seen not on MQTT more
it is on API
