### ISSUE TITLE
publishing events 

### ISSUE THREAD

**Issue by ra7bi** [Nerixyz/instagram_mqtt#113]
Hello , Thanks for amazing project , my question is ,

is it possible to publish an event for example sending Typing event or any other .?

Thank you.

**Comment by Nerixyz** [comment]
You can use [`realtime.direct.indicateActivity`](https://github.com/Nerixyz/instagram_mqtt/blob/0f80649a0f56fdb7550f9532488485b4b9f342f0/src/realtime/commands/direct.commands.ts#L252) but I don't know if it still works.

**Comment by ra7bi** [comment]
Thanks , also is it possible to share what is the version of Instagram APK you worked with ?  i tried to reverse engineering Instagram on android using Frida ( with patched APK - no ssl pinning )  i can see all the endpoints Restful api (http)  as plain but MQTT encrypted with TLS  , if possible share some information or hints . Thanks again

**Comment by Nerixyz** [comment]
There's a [small paragraph in the readme](https://github.com/Nerixyz/instagram_mqtt#research), so it seems like last time I updated it, I used v123. Last time I checked, you could also just use mitmproxy if you're in the whitehat mode.

**Comment by ra7bi** [comment]
i cant see in the readme , BTW i will try with v123 , 

i tried burp and Mitmproxy , the problem is i can see the entire app traffic except MQTT requests , so i was thinking there is another pinning for MQTT or kind of trick ,

 i will redo the test again

**Comment by Nerixyz** [comment]
> i cant see in the readme

I linked it to you above. I didn't use any proxy but intercepted the read/write calls of the app with frida.

**Comment by ra7bi** [comment]
i can confirm it's working 

> You can use [`realtime.direct.indicateActivity`](https://github.com/Nerixyz/instagram_mqtt/blob/0f80649a0f56fdb7550f9532488485b4b9f342f0/src/realtime/commands/direct.commands.ts#L252) but I don't know if it still works.
