### ISSUE TITLE
IgCookieNotFoundError: Cookie "sessionid" not found at State.extractCookieValue

### ISSUE THREAD

**Issue by loveyandex** [Nerixyz/instagram_mqtt#117]
in node_modules/instagram_mqtt/dist/realtime/realtime.client.js
u use   
```

  constructConnection() {
        const userAgent = this.ig.state.appUserAgent;
        const deviceId = this.ig.state.phoneId;
        const password = `sessionid=${this.ig.state.extractCookieValue('sessionid')}`;


```
```
ig.state.extractCookieValue("sessionid")
‌IgCookieNotFoundError: Cookie "sessionid" not found
```
 

i think sessionid is gone to 
`
ig.state.parsedAuthorization.sessionid
`

**Comment by NicksonYap** [comment]
https://github.com/Nerixyz/instagram_mqtt/pull/116/files

There is already a commit

but not sure if it was released

**Comment by Nerixyz** [comment]
> but not sure if it was released

See https://www.npmjs.com/package/instagram_mqtt and https://github.com/Nerixyz/instagram_mqtt/commit/f2672ac2c1167859e4fcc3a2d0f6a4660a33250b.
