### ISSUE TITLE
Examples of sending a message to Direct

### ISSUE THREAD

**Issue by sultanlive** [Nerixyz/instagram_mqtt#12]
Can I send messages to direct?
For example, as in [link](https://github.com/dilame/instagram-private-api/blob/3e1605831996c19e59f7b91461eea3539cd3521f/src/repositories/direct-thread.repository.ts#L223)

**Comment by Nerixyz** [comment]
You can do this via the http api (DirectThredEntity.broadcastText()) or via the real-time client (ig.realtime.direct.sendText({text, threadId}))

**Comment by sultanlive** [comment]
Thank you! This working for me

**Comment by us3rna7e** [comment]
> 

![image](https://user-images.githubusercontent.com/85359493/144741564-8ecaddc3-4d3b-4f11-a68f-532b1f2d7e85.png)
![image](https://user-images.githubusercontent.com/85359493/144741580-71eb4ab0-bbe5-4277-90ab-1fefe15e7587.png)

Unable to send direct message with ig.realtime.direct.sendText()

**Comment by dotpylove** [comment]
> You can do this via the http api (DirectThredEntity.broadcastText()) or via the real-time client (ig.realtime.direct.sendText({text, threadId}))

![image](https://user-images.githubusercontent.com/85359493/144741564-8ecaddc3-4d3b-4f11-a68f-532b1f2d7e85.png)
![image](https://user-images.githubusercontent.com/85359493/144741580-71eb4ab0-bbe5-4277-90ab-1fefe15e7587.png)

Unable to send direct message with ig.realtime.direct.sendText()

**Comment by rbjs** [comment]
Please provide working example of dm using real-time API. 
 await ig.realtime.direct.sendText(text, clientContext, threadId) doesn't work.

btw, clientContext == message.client_context ?

**Comment by Nerixyz** [comment]
> await ig.realtime.direct.sendText(text, clientContext, threadId) doesn't work.

The method takes an object, not a string. `sendText({text, clientContext, threadId})` (correct) ≠ `sendText(text, clientContext, threadId)` (incorrect).

Also some general advice: Consider using typescript or an editor that typeckecks your code (it should've warned you about passing a string). `clientContext` is almost never needed.

> btw, clientContext == message.client_context ?

Should be the case but don't quote me on that, since I haven't looked at it recently.
