### ISSUE TITLE
Is there support for direct messages with post content?

### ISSUE THREAD

**Issue by Iwasherd** [Nerixyz/instagram_mqtt#14]
Now when I receive a message with a post content, I get the following error
```
Error: Expected flags 0 but got 2
    at DisconnectRequestPacket.assertPacketFlags 
    at DisconnectRequestPacket.read 
   at tryCatcher
    at Function.Promise.attempt.Promise.try 
    at MqttParser.parse
    at async MQTToTClient.handleData
```
Can anyone help me with this issue please?

**Comment by Nerixyz** [comment]
Should be updated.
The message was longer than 1500bytes and my parser didn't parse that correctly.

**Comment by Iwasherd** [comment]
@Nerixyz  Thanks a lot. It works
