### ISSUE TITLE
Error while connecting fnbs for a second time for the same account

### ISSUE THREAD

**Issue by Ektaros** [Nerixyz/instagram_mqtt#15]
I am using this commands to stop my Instagram class instance
```
async stopInstagram() {
   await this.ig.realtime?.direct?.sendForegroundState({ inForegroundApp: false, inForegroundDevice: false, keepAliveTimeout: 900 })
   return this.ig.destroy()
}
```
But i could not find a way to stop fbns.

Then I try to create a new instance for the same account I connect once again and get this error (using version 0.1.13)
```
Cannot read property 'toString' of undefined
    at MQTToTClient.<anonymous> (C:\Users\mi\Documents\repos\channels-manager-instagram\node_modules\instagram_mqtt\src\fbns\fbns.client.ts:283:39) ...
```
This refers to this code if Im not mistaken
```
this.client.on('mqttotConnect', async (res) => {
            _fbnsDebug('Connected to MQTT');
            const payload = res.payload.toString('utf8');
...
```

So I logged the res object this is how it looks:
```
ConnectResponsePacket {
  packetFlags: 0,
  remainingPacketLength: 2,
  _packetType: 2,
  _flags: 0,
  _returnCode: 2
}
```

Any ideas how to fix it? Maybe stop fnbs somehow?

**Comment by Nerixyz** [comment]
Currently there's no way of disconnecting. I was going to implement it in the next few days.

**Comment by Ektaros** [comment]
Great! Looking forward to that moment, thanks.

**Comment by Nerixyz** [comment]
I've added a disconnect method. You can call `await ig.realtime.disconnect()` and then discard the client.

**Comment by Ektaros** [comment]
@Nerixyz Thanks a lot! This solved the problem.
