### ISSUE TITLE
Get pending messages

### ISSUE THREAD

**Issue by amirpdlll** [Nerixyz/instagram_mqtt#21]
Hello ;

Is there a way to get pending messages in real time ?

thanks

**Comment by Nerixyz** [comment]
This is done with the regular api. It's the directPending feed.

**Comment by amirpdlll** [comment]
thank you ,

For approving all directs and reading them which is the proper way ?

1. after ig.login I create a while with sleep (delay) and read pending directs every 1 minute 

2.I create a crontab or cronjob and lauch all the approve.js file every one minute?

thank you

**Comment by Nerixyz** [comment]
>     1. after ig.login I create a while with sleep (delay) and read pending directs every 1 minute

That's ok, there's probably a way of using FBNS for that, but this solution will work, you might have to increase the delay a bit.

**Comment by amirpdlll** [comment]
> > ```
> > 1. after ig.login I create a while with sleep (delay) and read pending directs every 1 minute
> > ```
> 
> That's ok, there's probably a way of using FBNS for that, but this solution will work, you might have to increase the delay a bit.

thank you so much ;)

**Comment by amirpdlll** [comment]
is it better to make random delay ? between 1 and 2 minutes ?

**Comment by amirpdlll** [comment]
> > ```
> > 1. after ig.login I create a while with sleep (delay) and read pending directs every 1 minute
> > ```
> 
> That's ok, there's probably a way of using FBNS for that, but this solution will work, you might have to increase the delay a bit.

is it better to make random delay ? between 1 and 2 minutes ?

**Comment by Nerixyz** [comment]
> 
> 
> > > ```
> > > 1. after ig.login I create a while with sleep (delay) and read pending directs every 1 minute
> > > ```
> > 
> > 
> > That's ok, there's probably a way of using FBNS for that, but this solution will work, you might have to increase the delay a bit.
> 
> is it better to make random delay ? between 1 and 2 minutes ?
I've used 2min in the past but longer/random delays are not bad.
