### ISSUE TITLE
Group message event

### ISSUE THREAD

**Issue by Superalexandre** [Nerixyz/instagram_mqtt#22]
Hello,

I search the event name when group message are received

Thanks :)

**Comment by Nerixyz** [comment]
> 
> 
> Hello,
> 
> I search the event name when group message are received
> 
> Thanks :)

You have to get the thread info. This can be done by getting the fist items of the thread. 
I've done this [here](https://github.com/Nerixyz/ig-discord-bridge/blob/8121aa1bb3dc00eda5da9e239c82bff78348bbcb/src/ThreadRegister.ts#L18).

**Comment by Superalexandre** [comment]
Okay thanks
