### ISSUE TITLE
Realtime comments tracking

### ISSUE THREAD

**Issue by shevchenko-max** [Nerixyz/instagram_mqtt#25]
Is it possible to track comments in realtime?

**Comment by Nerixyz** [comment]
I'm not sure, maybe through in-app notifications. But with fbns this should be at least partially possible.

**Comment by Ektaros** [comment]
Fbns works well enought for me. I also use modified comments request to get comments tree containing the required comment.

**Comment by shevchenko-max** [comment]
@Ektaros would be great if you could provide some example. I tried to use fbns but in some reason I didn't get any notification.

**Comment by Nerixyz** [comment]
@Ektaros What are your modifications and which component are they modifying?

**Comment by Ektaros** [comment]
@shevchenko-max Yes there is such problem but it is rare. I just never get notifications from some accounts. 
@Nerixyz I add targer_comment_id field to MediaCommentsFeed request from instagram-private-api lib. This almost always gives back a tree with the comment i need.
