### ISSUE TITLE
Experiencing breakages in other packages based on Instagram API

### ISSUE THREAD

**Issue by kaanuki** [Nerixyz/instagram_mqtt#27]
Hi.

As Instagram moves closer to completely shutting off access to its public API endpoints, I am experiencing breakages in some of the other packages that relied on the Instagrams API, such as 'Instagram-profile-picture'. It's now dead.

Is this currently package experiencing any problems or downtime? Will it possibly experience any problems once Instagram's hard cut-off date of March 31st arrives?

**Comment by Androz2091** [comment]
Hello, the package works perfectly for me.

**Comment by Nerixyz** [comment]
I don't know how many times I have to say this, but this package only used the *private* API (which is also used by the app). So there's no deprecation to be expected.

**Comment by kaanuki** [comment]
> I don't know how many times I have to say this, but this package only used the _private_ API (which is also used by the app). So there's no deprecation to be expected.

Ok. Thanks for clarifying that.  But i don't understand how a "private" api can go undetected by Instagram,  especially for things like posting. Can they discern the difference in the interactions of this private api and their own actual api?
