### ISSUE TITLE
Subscribe event?

### ISSUE THREAD

**Issue by Androz2091** [Nerixyz/instagram_mqtt#4]
Hey. First of all, thank you very much for the work you have done, without which I don't know what I would have done 😁 
I want to know if it's possible to have a `subscribe` event when someone starts following you. Actually, I make one request every 5 seconds to compare cache and Instagram values (I check if there is a new person in the followers array). But it will be better to have mqtt support for this feature.
Is it possible actually? Or is it planned?
Thanks again, I don't know how to thank you.

**Comment by Nerixyz** [comment]
This can be done by using notifications (although it may be unstable as I don't know how it behaves with a large amount of followers):
```ts
// data.actionParams.username should contain the username
    fbns.on('new_follower', data => console.log(data));
```
Assuming `fbns` is an instance of [FbnsClient](https://github.com/Nerixyz/instagram_mqtt/blob/master/examples/push.example.ts).

**Comment by Androz2091** [comment]
Oh nice! I will try it. I didn't see this very useful file https://github.com/Nerixyz/instagram_mqtt/blob/master/src/fbns/fbns.client.ts.
Thank you for your help!
