### ISSUE TITLE
problem with fbns_msg topic

### ISSUE THREAD

**Issue by BehzadArabi** [Nerixyz/instagram_mqtt#46]
Hello. I had trouble implementing mqtt to receive notifications. This problem has nothing to do with your library, and I make a issue so in the hope that you will have an answer for me.
I did all the steps correctly and did the `Push Register` with token and got the right answer, but I don't get the notifications.
Do you have any idea how I can fix this problem?

I didn't use your library because I wanted to implement it for ios/android platform

**Comment by Nerixyz** [comment]
Make sure your MQTT implementation is valid and you're sending a valid initial connect packet. Else I can't really help you.

**Comment by BehzadArabi** [comment]
I do all the steps correctly. And finally, I get this information `{"k":"eyJwbiI6ImNvbS5pbnN0YWdyYW0u5kcm9pZCIsImRpIjoiYWE4MjBkNjUtOGFjNS00ZjAxLWFkNzAtNzJjYjRlM2U1NGVjIiwiYWkiOjU2NzA2NzM0MzM1MjQyNywiY2siOiI0NTU3MDQzODExMDIxMjkifQ==","v":0,"t":"fbns-b64"}`. I think I have a problem with the pushRegister. Can I talk with you in telegram?

**Comment by idb-** [comment]
> I do all the steps correctly. And finally, I get this information `{"k":"eyJwbiI6ImNvbS5pbnN0YWdyYW0u5kcm9pZCIsImRpIjoiYWE4MjBkNjUtOGFjNS00ZjAxLWFkNzAtNzJjYjRlM2U1NGVjIiwiYWkiOjU2NzA2NzM0MzM1MjQyNywiY2siOiI0NTU3MDQzODExMDIxMjkifQ==","v":0,"t":"fbns-b64"}`. I think I have a problem with the pushRegister. Can I talk with you in telegram?

have you figured this all out?

**Comment by Nerixyz** [comment]
> have you figured this all out?

This might be related to #67

**Comment by idb-** [comment]
Is there some place where I could speak to you directly? I tweeted you the
other day but not sure if you're active on there or not.

**Comment by Nerixyz** [comment]
> I tweeted you the other day but not sure if you're active on there or not.

I didn't see it.

**Comment by idb-** [comment]
> > I tweeted you the other day but not sure if you're active on there or not.
> 
> I didn't see it.

i just checked and apparently it never got posted. is twitter your preferred medium to talk on here or do you have a discord/skype/telegram i can reach you at?
