### ISSUE TITLE
No support for ig.realtime.direct.broadcastPhoto() and ig.realtime.direct.broadcastVideo() yet?

### ISSUE THREAD

**Issue by iMrDJAi** [Nerixyz/instagram_mqtt#47]
I see there is no function to broadcast media to threads [here](https://github.com/Nerixyz/instagram_mqtt/blob/master/src/realtime/commands/direct.commands.ts), any plans to add that? and what's the best alternative for now?

**Comment by Nerixyz** [comment]
> any plans to add that?

Photos and Videos are sent via HTTP. Or did you find a packet for it?

**Comment by iMrDJAi** [comment]
Not really, I'm just asking. I didn't even know that there is no known packet for that.
Yeah I got it, know I'm sending photos and videos via HTTP.
