### ISSUE TITLE
Questions about the RTC

### ISSUE THREAD

**Issue by bvanhou** [Nerixyz/instagram_mqtt#5]
Does the realtime Chat currently work?

**Comment by Nerixyz** [comment]
Yes, [this](https://github.com/Nerixyz/instagram_mqtt/blob/master/examples/realtime.example.ts) example should be up to date.

**Comment by bvanhou** [comment]
Additionally this is random, are you hirable? I have an issue I cannot seem to fix and I would love to hire you to help me implement RTC

**Comment by Nerixyz** [comment]
Actually I've never really designed a server-client protocol/contract, I've only implemented it on the client side. If this isn't related to Instagram, I'll have to decline this.

**Comment by bvanhou** [comment]
ohh its completely for instagram

**Comment by bvanhou** [comment]
I just need help, connecting the dots.

**Comment by Nerixyz** [comment]
Then if it's also related to realtime-data (mqtt, fbns etc.) and doesn't reveal personal information, you can ask your questions here.

**Comment by bvanhou** [comment]
Great! Thanks

**Comment by bvanhou** [comment]
Is there a reason behind not utilizing the npm package : https://www.npmjs.com/package/graphql

**Comment by Nerixyz** [comment]
Because it's currently not using graph ql queries.

**Comment by bvanhou** [comment]
One more question, is a database required/reocmmended to use this? Or are we just leveraging instagram apis

**Comment by Nerixyz** [comment]
There's not database required.
