### ISSUE TITLE
Problem by module re2 

### ISSUE THREAD

**Issue by phamngocthanhtrung** [Nerixyz/instagram_mqtt#56]
i can't get the instagram_mqtt module to install correctly. when i do npm install it freezes with this message 

```bash
> re2@1.15.9 install /home/n01pham/Desktop/insta-api/fbns/node_modules/re2
> install-from-cache --artifact build/Release/re2.node --host-var RE2_DOWNLOAD_MIRROR || npm run rebuild

Trying https://github.com/uhop/node-re2/releases/download/1.15.9/linux-x64-83.br ...
```
My operating system is Ubuntu 18.04.

**Comment by Nerixyz** [comment]
This is a problem of `instagram-private-api`. And even there, it's rather a problem related to `re2`.
