### ISSUE TITLE
Error: Cannot find module 'node-cint64'

### ISSUE THREAD

**Issue by ammar-sheikh** [Nerixyz/instagram_mqtt#6]
Hi, 

I just installed this repo using 
`npm install instagram_mqtt`

but i'm getting this error : Cannot find module 'node-cint64'

node version: v12.13.1

package.json: 
```
  "dependencies": {
    "bluebird": "^3.7.1",
    "inquirer": "^7.0.0",
    "instagram-private-api": "^1.33.0",
    "instagram_mqtt": "^0.1.7"
  }
```

Note: still didn't do anything with library just requiring it throw this error

**Comment by Nerixyz** [comment]
I had an old reference to node-cint64. Sorry I somehow didn't catch that.
Should be fixed in *0.1.8*.
You can run `npm install instagram_mqtt` to update.
