### ISSUE TITLE
Cannot connect from different IP's at the same time

### ISSUE THREAD

**Issue by andresespinosapc** [Nerixyz/instagram_mqtt#61]
When I connect to realtime, then I connect with the same account (different sessions) from a different IP, I get disconnected from the other session. The error I get is `ClientDisconnectedError: MQTToTClient got disconnected`.

When I say different IP I really mean it, I'm doing it from localhost and a Heroku server.

What could make Instagram think I'm connecting from the same place or something like that? Maybe some header or device information that is the same for both connections.

**Comment by Nerixyz** [comment]
> What could make Instagram think I'm connecting from the same place or something like that?

> Maybe some header or device information that is the same for both connections.

You're probably using the same session or the same device.

**Comment by andresespinosapc** [comment]
Yeah, the problem was using the same seed to generate device (the username).
