### ISSUE TITLE
[REQUEST] Instagram client version update

### ISSUE THREAD

**Issue by arianaglande** [Nerixyz/instagram_mqtt#63]
Hey, basically when receiving media such as reels in dm I figured out that I was just receiving a message with that text in it “Download the most recent update to view this message”. May you update the client version to the latest one (if possible)? Thanks!

**Comment by Nerixyz** [comment]
You're probably on the wrong repository. This repository uses the constants provided by the [`instagram-private-api`](https://github.com/dilame/instagram-private-api).
