### ISSUE TITLE
Realtime not binding to local address.

### ISSUE THREAD

**Issue by yblok13** [Nerixyz/instagram_mqtt#65]
In IgApiClient I'm binded to a local address of a hotspot I have, which works as expected. 
`ig.request.defaults.localAddress = x.x.x.x`
Though, `ig.realtime.connect({...})` doesn't seem to use that address.

**Comment by Nerixyz** [comment]
You can use `ig.realtime.connect({additionalTlsOptions: {localAddress: ... }})`
