### ISSUE TITLE
not getting notification when new follower follow me

### ISSUE THREAD

**Issue by ammar-sheikh** [Nerixyz/instagram_mqtt#7]
I want to receive notification when new follower follow my account but it doesn't seem working 
this is my code : 

```
// auth 
  ig.fbns.on("push", logEvent("push"));

  ig.fbns.on("message", logEvent("message"));

  ig.fbns.on("new_follower", notification => {
    console.log("new_follower", notification);
  });
  await ig.fbns.connect();
```
btw : I am able to receive notification when someone dm me

**Comment by Nerixyz** [comment]
This is an issue with fbns itself. It is directly responsible for the notifications so to avoid notification spam, it 'hides' some notifications (you may have noticed this on your own instagram account).

**Comment by ammar-sheikh** [comment]
How about subscribing to followers count...  If followers count changed I want to do something 
I don't know if it is possible or not
What do you think?

**Comment by ammar-sheikh** [comment]
@Nerixyz can I get reatime followers count?

**Comment by Nerixyz** [comment]
No, unfortunately that's not possible.
