### ISSUE TITLE
Skip patch event notification

### ISSUE THREAD

**Issue by realrecordzLab** [Nerixyz/instagram_mqtt#71]
Using the `message` event, is possible to skip notifications about `patch` events? Is there any code example?

I'm trying with this code but not sure if will work as expected: 
```js
    ig.realtime.on('message', (message) => { 
       if(  message.event === 'patch' ){
          return;
       }
       ....
    });
```
Is there any documentations about the events that are provided with `message` object? How is the correct way to get informations about the thread and the users that is emitting the `patch` event?

**Comment by Nerixyz** [comment]
> Is there any documentations about the events that are provided with `message` object?

Besides the types there's no documentation.

> How is the correct way to get informations about the thread and the users that is emitting the `patch` event?

You get a thread id which can be used to look up informations about a thread. In a real application you'd probably cache the thread infos.

>  not sure if will work as expected:

If you don't want to handle the `patch` event, then it's fine.

**Comment by realrecordzLab** [comment]
> You get a thread id which can be used to look up informations about a thread. In a real application you'd probably cache the thread infos.

With this code I get the thread ID
```js
    ig.realtime.on('message', async (message) => { 
        console.log(message);
        const thread = await ig.entity.directThread(message.message.thread_id);
        console.log(thread); 
    });
    ``` 
What's the correct method to use for specific thread info?    
    
> If you don't want to handle the `patch` event, then it's fine.

I've noticed that all the events including new messages are grouped under the `patch` method so by skipping it no message info are logged

**Comment by realrecordzLab** [comment]
Found a solution to get the thread info after searching in the issues. 
```js
    ig.realtime.on('message', async (data) => { 
        const thread = await ig.feed.directThread({thread_id: data.message.thread_id}).request();
        console.log(thread);
    });
```
With this code I'm able to get thread info but the problem is that I will also get messages I send to the other user.  Is there any field that I can use to get only messages that are sent to me from the other user?

**Comment by Nerixyz** [comment]
> Is there any field that I can use to get only messages that are sent to me from the other user?

```ts
    ig.realtime.on('message', async ({message}) => { 
        if(message.user_id.toString() === ig.state.cookieUserId) return;
        console.log(message);
    });
```


> Found a solution to get the thread info after searching in the issues.

Be careful. This will always request the thread from instagram. The app doesn't do that. You should cache the thread.

**Comment by realrecordzLab** [comment]
> > Is there any field that I can use to get only messages that are sent to me from the other user?
> 
> ```ts
>     ig.realtime.on('message', async ({message}) => { 
>         if(message.user_id.toString() === ig.state.cookieUserId) return;
>         console.log(message);
>     });
> ```
> 
> > Found a solution to get the thread info after searching in the issues.
> 
> Be careful. This will always request the thread from instagram. The app doesn't do that. You should cache the thread.

At the moment I'm requesting the thread only for new messages when received. Maybe a solution can be to store each `thread_id` into an array? I'm confused about caching implementation in my CLI script
