### ISSUE TITLE
Log messages reactions

### ISSUE THREAD

**Issue by realrecordzLab** [Nerixyz/instagram_mqtt#72]
How reactions to messages can be logged? 
I'm trying to switch the `item_type` but without success

```js
    switch(data.message.item_type){
        case 'text':    
            break;
        case 'voice_media':
            break;
        case 'like':
            break;
    }
```
Is correct to use the `item_type` field or I need to check for another field?

**Comment by Nerixyz** [comment]
I think it's `'like'` but you can always debug the code and look at the object yourself.

**Comment by realrecordzLab** [comment]
> I think it's `'like'` but you can always debug the code and look at the object yourself.

I've debugged the `message` object and the `item_type` when a reaction is added will not change from `text`, it will be added a `reactions` field to the object. Maybe the `like` type is used for something else I think?

**Comment by andresespinosapc** [comment]
@realrecordzLab What version are you using? I'm not getting the `reactions` property
