### ISSUE TITLE
Direct Message Thread Example

### ISSUE THREAD

**Issue by bvanhou** [Nerixyz/instagram_mqtt#8]
Do you have any examples of this being implemented on the client side for direct messages on a specific thread?

**Comment by Nerixyz** [comment]
This isn't per thread as I know, it's "global". What you're probably interested in is getting live dms (or usertyping).
This can be done, by adding the `irisData` like in this example:
https://github.com/Nerixyz/instagram_mqtt/blob/52b8c548879c67d443f03a2291b3a94840d23b92/examples/realtime.example.ts#L44
You can then go ahead and listen to the `message` event:
https://github.com/Nerixyz/instagram_mqtt/blob/52b8c548879c67d443f03a2291b3a94840d23b92/examples/realtime.example.ts#L23

This will yield you an object of the [type `MessageSyncMessageWrapper`](https://github.com/Nerixyz/instagram_mqtt/blob/master/src/realtime/messages/message-sync.message.ts) which contains a `message`.
So in your code you can destructure it like this to get the actual data: 
```ts
ig.realtime.on('message', ({message}) => console.log(message));
```

**Comment by bvanhou** [comment]
I am attempting to get this to run locally however the connection keeps closing. Is there any advance error handling?

```
wscat -c ws://localhost:3001
Connected (press CTRL+C to quit)
< {"message":"Internal server error","connectionId":"ck3rp7l8i000b1gyc2pl28pt1","requestId":"1234567890"}
Disconnected (code: 1005, reason: "")
```

**Comment by Nerixyz** [comment]
How are you using websocktes? The conection to Instagram is managed by the RealtimeClient.

**Comment by bvanhou** [comment]
So maybe this is just due to my extreme lack of experience in this area and I am not sure if this is the right idea even to start. But its more trail by fire.

I am attempting to create a websocket connection to my frontend that intern leverages your ig RealtimeClient. The purpose of this is to have a solid connection when chatting from my front end.

Front <=> Websocket <=> RealtimeChat

**Comment by bvanhou** [comment]
So after random troubleshooting. I have found the issue and resolved the issue. Altering the line referenced below allow this to work

From:
`import Chance = require('chance');
`To:
`import * as Chance from 'chance';
`
https://github.com/Nerixyz/instagram_mqtt/blob/52b8c548879c67d443f03a2291b3a94840d23b92/src/realtime/subscriptions/graphql.subscription.ts#L1

**Comment by Nerixyz** [comment]
This should not produce any errors as it's very similar if not the same. If you could paste your error here it would be helpful.

**Comment by bvanhou** [comment]
It specifically did not like this line. It would not produce any results. Once I did the fix above I have not had any issues. Correct me if I am wrong, though when you are using require you need to toss it in memory as a 'var' or 'const'. It is getting confused by the import.

`options.subscriptionId || new Chance().guid({ version: 4 }),`

**Comment by Nerixyz** [comment]
I think import = require was added in Typescript 2.2 and thus should work fine. If you have the specific error please paste it here.

**Comment by Nerixyz** [comment]
> It is getting confused by the import, though that just may be the difference between Node implementation and front end ES6 perhaps?

I've just compared them:
Both `import Chance = require('chance')` and `import * as Chance from 'chance'` will transpile to `const Chance = require("chance");`, so there's no difference.
Your error would still be interesting

**Comment by bvanhou** [comment]
So maybe its due to the serverless framework, I am using however the code below produces nothing when I switch to the original configuration.

`new Chance().guid({ version: 4 })`


`Import assignment cannot be used when targeting ECMAScript modules. Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead.ts(1202)`

**Comment by bvanhou** [comment]
If you want I can give you access so you can review yourself.

**Comment by Nerixyz** [comment]
This may fix your issue: https://stackoverflow.com/a/40737544/7014712

**Comment by bvanhou** [comment]
Unfortunately, it did not. However, I saw that you updated the code. Thank you! Though, the realtime example is off now. We need the ability to reference GraphQLSubscriptions and SkywalkerSubscriptions. Perhaps something like below.


```
import { 
      withRealtime , 
      GraphQLSubscriptions, 
       SkywalkerSubscriptions } from 'instagram_mqtt';
```

Error: 
`node_modules/instagram_mqtt/dist"' has no exported member 'GraphQLSubscriptions'.`

**Comment by Nerixyz** [comment]
Currently, you can import them from 
```
'instagram_mqtt/dist/realtime/subscriptions/graphql.subscription' 
```

**Comment by bvanhou** [comment]
thanks

**Comment by bvanhou** [comment]
Perfect! Everything is working like a charm!! Thank you for your help with this

**Comment by bvanhou** [comment]
One additional thing. Does the 'chance' module need to be part of the package.json?

**Comment by bvanhou** [comment]
Lastly, I had to include the change module in the npm package instagram_mqtt.

```
  "dependencies": {
    "chance": "^1.1.4", //Added 
    "instagram-private-api": "^1.34.0",
    "lodash": "^4.16.6"
  },
```
