### ISSUE TITLE
TypeError: stream.on is not a function 

### ISSUE THREAD

**Issue by callmearta** [Nerixyz/instagram_mqtt#81]
Hi, I've been trying for couple hours now to get your library working. I'm using instagram-private-api and it's working fine and returns direct messages and everything. Although when i try to use your library this happens:
```
/src/node_modules/eventemitter3/index.js:181 TypeError: stream.on is not a function
    at destroyer (internal/streams/pipeline.js:27)
    at internal/streams/pipeline.js:88
    at Array.map (<anonymous>)
    at Function.pipeline (internal/streams/pipeline.js:85)
    at MQTToTClient.createPipeline (mqtt.client.ts:167)
    at MQTToTClient._connect (mqtt.client.ts:150)
    at async MQTToTClient.connect (mqtt.client.ts:157)
```

I'm using this line to wrap the IgApiClient:
```
withFbnsAndRealtime(new IgApiClient())
```

Could you help me out please?
Also I'm using electron, maybe there's something happening in there.

**Comment by Nerixyz** [comment]
Which Node version are you on?

**Comment by callmearta** [comment]
14.15.0

**Comment by Nerixyz** [comment]
Then what's your code? 

Also make sure you turn on [debugging](https://github.com/Nerixyz/instagram_mqtt#debugging).

**Comment by callmearta** [comment]
<img width="1010" alt="Screen Shot 2021-06-01 at 16 43 49" src="https://user-images.githubusercontent.com/19687043/120321445-8e4cae00-c2f8-11eb-9f9a-9766e399c1ee.png">
This is the screenshot of the error. also i tried using debugging but no more information came out of it. So i think something goes wrong before it reaches your lib to debug it. Are the examples up to date with latest version of instagram-private-api? I think maybe there's something happening.
this is my code:
```
const = withFbnsAndRealtime(new IgApiClient());
ig.state.generateDevice(username);
  await ig.simulate.preLoginFlow();
...LoginThings....
ig.realtime.on('error', console.error);
  ig.realtime.on('receive', console.log);
  await ig.realtime.connect();
```

**Comment by Nerixyz** [comment]
Are you running this in the browser or the background process?

**Comment by callmearta** [comment]
I'm running it in react wrapped in electron js so it should be running in browser. Although i can't see the request in network tab

**Comment by Nerixyz** [comment]
This library relies on node-streams, so you can't run it in the browser. Furthermore, it uses raw TCP/TLS to connect to Instagram which the browser just cannot do.

**Comment by callmearta** [comment]
Let me check to assure. At the time being thank you for responding. I think it's running under node because it's request is not visible in networks tab

**Comment by callmearta** [comment]
@Nerixyz I checked it and it's running under node not browser. Still getting this error when using latest version of your package:
```
index.js:181 TypeError: stream.on is not a function
    at destroyer (internal/streams/pipeline.js:27)
    at internal/streams/pipeline.js:88
    at Array.map (<anonymous>)
    at Function.pipeline (internal/streams/pipeline.js:85)
    at MQTToTClient.createPipeline (mqtt.client.js:110)
    at MQTToTClient._connect (mqtt.client.js:95)
    at async MQTToTClient.connect (mqtt.client.js:100)
```

**Comment by Nerixyz** [comment]
Did you try it in vanilla-node?

**Comment by callmearta** [comment]
@Nerixyz No. I tried to test your own example but couldn't get it working because of no babel or webpack. Still that old version doesn't throw this error. But also that one doesn't work. I've been stuck for almost 7 hours now :))

**Comment by Nerixyz** [comment]
> because of no babel or webpack

You don't need babel or webpack. You just need typescript. Just do `npm i instagram_mqtt instagram-private-api` edit some constants and run it.

**Comment by callmearta** [comment]
I did what you said and it works. Then why doesn't it work when it's wrapped in electron?

**Comment by callmearta** [comment]
Yea there's definitely something wrong with wrapping in electron. do you have any suggestions?

**Comment by Nerixyz** [comment]
> 14.15.0

That's wrong. You've used Node 12 (See [this run on node 12](https://github.com/Nerixyz/mqtts/runs/2155452691); the next run on node 14 was sucessful)

**Comment by callmearta** [comment]
<img width="568" alt="Screen Shot 2021-06-01 at 19 52 58" src="https://user-images.githubusercontent.com/19687043/120349011-f7d9b600-c312-11eb-9a4a-bad77f50bb12.png">
@Nerixyz It says 14.15.0 mate. Also i've tried installing node again and it succeeded.

**Comment by Nerixyz** [comment]
> It says 14.15.0 mate. Also i've tried installing node again.

Yeah but there's no version of Node 14 where there's a call to `stream.on` (the stacktrace you sent) on line 27 in `internal/streams/pipeline.js`.

**Comment by callmearta** [comment]
Finally!!!!!! Thank you mate. The problem was the fact that electron had packed it's own version of Node and was using version 12.8! I didn't know it does such a thing. Finally after 12 hours :)) Thanks again

**Comment by F145h** [comment]
thanks for you answers. electron@12 is fine!
