### ISSUE TITLE
Not getting reels in realtime response

### ISSUE THREAD

**Issue by dotpylove** [Nerixyz/instagram_mqtt#90]
![image](https://user-images.githubusercontent.com/91171375/144246165-71ebe793-9773-4e6f-a9f7-b60b30173713.png)

**Comment by Nerixyz** [comment]
The version and capabilities your client is emulating is too old. 

This isn't a problem with this library, they should be updated in the `instagram-private-api`.

**Comment by Nerixyz** [comment]
> My question is can we get the details about that reel using its item_id ?

You should be able to get info using the media/info endpoint and by providing this media-id.

**Comment by Nerixyz** [comment]
> If yes, i can't find media id. In this response.

If you get an item that's a reel (not a placeholder), it should have a media-id.
