### ISSUE TITLE
realtime client doesnt work in v1

### ISSUE THREAD

**Issue by Tyrone5693** [Nerixyz/instagram_mqtt#96]
i was using v0 and events was working good but when i upgrade it to v1 it stopped working
```
    ig.realtime.on("receive", (topic, messages) => {
      this.handleRealtimeReceive(topic, messages);
    });
    ig.realtime.on("error", console.error);
    ig.realtime.on("close", () => console.error("RealtimeClient closed"));

    await ig.realtime.connect({
      // this enables you to get direct messages
      irisData: await ig.feed.directInbox().request(),
    });
```
nothing happens when i dm to bot

**Comment by Tyrone5693** [comment]
bug

**Comment by Nerixyz** [comment]
You're only listening on `receive` which is emitted for topics that don't have a specific parser. Take a look at the [example](https://github.com/Nerixyz/instagram_mqtt/blob/master/examples/realtime.example.ts#L16-L20).

**Comment by Nerixyz** [comment]
I don't see a use-case for this. But if you really want to listen to everything the client receives, listen to _message_ on the mqtt client: `ig.realtime.mqtt.on('message', ...)`.

But as I said, I don't see a use-case for this. Everything is already logged and to handle specific topics you'd branch in your code anyways since the messages don't share a common structure.

**Comment by Nerixyz** [comment]
It looks like you only want the direct messages. If that's the case, use `ig.realtime.on('message', fn)`. Where with `fn`, you can do something like this:

```js
ig.realtime.on('message', ({message: data}) => {
  switch (data.op) { /* ... */ }
});
```

See [`MessageSyncMessageWrapper`](https://github.com/Nerixyz/instagram_mqtt/blob/master/src/realtime/messages/message-sync.message.ts#L4-L6) and [`MessageSyncMessage`](https://github.com/Nerixyz/instagram_mqtt/blob/master/src/realtime/messages/message-sync.message.ts#L47-L83).

**Comment by Tyrone5693** [comment]
Okay thanks
